/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorVentanaMenu;
import javax.swing.*;
import modelo.base_de_datos.ProductoDAO;

/**
 *
 * @author Badal
 */
public class Menu extends javax.swing.JPanel {

  /**
   * Creates new form Prueba
   */
  ControladorVentanaMenu cvm;
  public Menu() {
    initComponents();
    ProductoDAO prDAO = new ProductoDAO();
    cvm = new ControladorVentanaMenu(this,prDAO);
    cvm.actualizarTabla();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pFondo = new javax.swing.JPanel();
    lMenu = new javax.swing.JLabel();
    Añadir = new javax.swing.JLabel();
    bEliminar = new javax.swing.JButton();
    spMenu = new javax.swing.JScrollPane();
    tMenu = new javax.swing.JTable();
    pAñadir = new javax.swing.JPanel();
    lNombre = new javax.swing.JLabel();
    lPrecio1 = new javax.swing.JLabel();
    lTipo = new javax.swing.JLabel();
    tfNombre = new javax.swing.JTextField();
    tfPrecio = new javax.swing.JTextField();
    bAñadir = new javax.swing.JButton();
    cbTipo = new javax.swing.JComboBox<>();

    setMaximumSize(new java.awt.Dimension(1210, 530));
    setMinimumSize(new java.awt.Dimension(1210, 530));
    setPreferredSize(new java.awt.Dimension(1210, 530));

    pFondo.setBackground(new java.awt.Color(225, 218, 206));
    pFondo.setPreferredSize(new java.awt.Dimension(1210, 530));

    lMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lMenu.setForeground(new java.awt.Color(0, 0, 0));
    lMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lMenu.setText("MENÚ");

    Añadir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    Añadir.setForeground(new java.awt.Color(0, 0, 0));
    Añadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Añadir.setText("AÑADIR");

    bEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    bEliminar.setForeground(new java.awt.Color(255, 102, 102));
    bEliminar.setText("ELIMINAR");
    bEliminar.setOpaque(true);
    bEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bEliminarActionPerformed(evt);
      }
    });

    tMenu.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Id", "Nombre", "Tipo", "Precio"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    spMenu.setViewportView(tMenu);
    if (tMenu.getColumnModel().getColumnCount() > 0) {
      tMenu.getColumnModel().getColumn(0).setMaxWidth(40);
      tMenu.getColumnModel().getColumn(1).setMinWidth(400);
    }

    pAñadir.setBackground(new java.awt.Color(255, 255, 255));
    pAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    lNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lNombre.setForeground(new java.awt.Color(0, 0, 0));
    lNombre.setText("Nombre:");

    lPrecio1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lPrecio1.setForeground(new java.awt.Color(0, 0, 0));
    lPrecio1.setText("Precio:");

    lTipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lTipo.setForeground(new java.awt.Color(0, 0, 0));
    lTipo.setText("Tipo:");

    tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    tfPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    bAñadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    bAñadir.setForeground(new java.awt.Color(0, 0, 0));
    bAñadir.setText("AÑADIR");
    bAñadir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bAñadirActionPerformed(evt);
      }
    });

    cbTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Bebida" }));
    cbTipo.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        cbTipoFocusGained(evt);
      }
    });
    cbTipo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbTipoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pAñadirLayout = new javax.swing.GroupLayout(pAñadir);
    pAñadir.setLayout(pAñadirLayout);
    pAñadirLayout.setHorizontalGroup(
      pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAñadirLayout.createSequentialGroup()
        .addContainerGap(15, Short.MAX_VALUE)
        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(bAñadir)
          .addGroup(pAñadirLayout.createSequentialGroup()
            .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(lNombre)
              .addComponent(lPrecio1)
              .addComponent(lTipo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(tfNombre)
              .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(15, 15, 15))
    );
    pAñadirLayout.setVerticalGroup(
      pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pAñadirLayout.createSequentialGroup()
        .addContainerGap(69, Short.MAX_VALUE)
        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lNombre)
          .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lPrecio1))
        .addGap(18, 18, 18)
        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lTipo)
          .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(47, 47, 47)
        .addComponent(bAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(59, 59, 59))
    );

    javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
    pFondo.setLayout(pFondoLayout);
    pFondoLayout.setHorizontalGroup(
      pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pFondoLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(pFondoLayout.createSequentialGroup()
            .addComponent(lMenu)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(spMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(44, 44, 44)
        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Añadir))
        .addContainerGap(47, Short.MAX_VALUE))
    );
    pFondoLayout.setVerticalGroup(
      pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pFondoLayout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bEliminar))
        .addGap(11, 11, 11)
        .addComponent(spMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(22, Short.MAX_VALUE))
      .addGroup(pFondoLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(pAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(81, 81, 81))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
    cvm.eliminarProducto();
  }//GEN-LAST:event_bEliminarActionPerformed

  private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
   cvm.añadirProducto();
    
  }//GEN-LAST:event_bAñadirActionPerformed

  private void cbTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTipoFocusGained

  }//GEN-LAST:event_cbTipoFocusGained

  private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
    // TODO add your handling code here:

  }//GEN-LAST:event_cbTipoActionPerformed


  public JTable getTabla(){
    return tMenu;
  }
  
  public String getNombre(){
    return tfNombre.getText();
  }
  
  public String getPrecio(){
    return tfPrecio.getText();
  }
  
  public String getTipo(){
    return (String) cbTipo.getSelectedItem();
  }
  
  public JButton getInsert(){
    return bAñadir;
  }
  
  public int[] getProductosAEliminar(){
    return tMenu.getSelectedRows();
  }
  
  
        
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Añadir;
  private javax.swing.JButton bAñadir;
  private javax.swing.JButton bEliminar;
  private javax.swing.JComboBox<String> cbTipo;
  private javax.swing.JLabel lMenu;
  private javax.swing.JLabel lNombre;
  private javax.swing.JLabel lPrecio1;
  private javax.swing.JLabel lTipo;
  private javax.swing.JPanel pAñadir;
  private javax.swing.JPanel pFondo;
  private javax.swing.JScrollPane spMenu;
  private javax.swing.JTable tMenu;
  private javax.swing.JTextField tfNombre;
  private javax.swing.JTextField tfPrecio;
  // End of variables declaration//GEN-END:variables
}
